app.repository.type=database
app.database.driver=com.mysql.cj.jdbc.Driver
app.database.url=jdbc:mysql://localhost:3306/quantity-measurement-db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
app.database.username=root
app.database.password=S@18052004
app.database.pool.size=4

