server:
  port: ${PORT:8083}

spring:
  application:
    name: measurement-service
  datasource:
    url: jdbc:h2:mem:measurementdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://qma-eureka-server-k1sl.onrender.com/eureka/}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
